Wording : renommer "clôturer" par "archiver"
betagouv/aplus pull request #813
Opened 2020-10-29 14:37 UTC by mdulac

2020-10-29 14:48 UTC, Aurelie-J requested changes
- On enlèverait pas le bouton Archiver qui se trouve sous la description de la demande à gauche ?

- Possible de faire en sorte que les 2 boutons Archiver la demande en haut et en bas est la même taile ?

2020-10-29 15:40 UTC, mdulac commented
> * On enlèverait pas le bouton Archiver qui se trouve sous la description de la demande à gauche ?
> * Possible de faire en sorte que les 2 boutons Archiver la demande en haut et en bas aient la même taile ?

Pour le 1, comme vu ensemble, ça me convient largement.
Pour le 2, je regarde plus tard, c'est pas si anodin (compte tenu de mon expertise en front), car il faut retravailler tout le bouton tel que c'est actuellement fait. Mais on garde ça sous le coude (pas urgent)

2020-10-29 15:40 UTC, mdulac commented
![Uploading Capture d’écran 2020-10-29 à 16.40.34.png…]()

2020-10-29 15:41 UTC, mdulac commented
<img width="963" alt="Capture d’écran 2020-10-29 à 16 40 34" src="https://user-images.githubusercontent.com/1923376/97596923-8d236d80-1a05-11eb-8b34-0441d0fe583c.png">

2020-11-02 13:48 UTC, niladic reviewed
Il faudrait mettre des apostrophes courbes ’ lorsqu'elles sont présentées aux utilisateurs

2020-11-02 13:48 UTC, niladic commented on app/views/emails/common.scala
> +        if (infos.applicationsThatShouldBeClosed.size <= 1) "l'archiver, " else "les archiver, ",
```suggestion
        if (infos.applicationsThatShouldBeClosed.size <= 1) "l’archiver, " else "les archiver, ",
```

2020-11-02 13:48 UTC, niladic commented on app/views/myApplications.scala.html
> +            (Elles seront supprimées 1 mois après l'archivage.)</div>
```suggestion
            (Elles seront supprimées 1 mois après l’archivage.)</div>
```

2020-11-03 07:57 UTC, Aurelie-J approved these changes

2020-11-03 14:02 UTC, merged