Ajoute les groupes dans les demandes
betagouv/aplus pull request #820
Opened 2020-11-02 20:02 UTC by niladic

En cours, il reste des petits fix UI à faire et à tester IE... puis gérer le modèle en scala

2020-11-09 19:34 UTC, jdauphant reviewed
Il y a peut être la notion du groupe demandeur à avoir

2020-11-16 10:24 UTC, mdulac requested changes

2020-11-16 10:37 UTC, niladic commented on app/models/Answer.scala
> +    invitedGroupIds: Option[List[UUID]],
oui, je vais attends le merge de https://github.com/betagouv/aplus/pull/824 pour me rebase dessus, ce sera plus pratique

2020-11-16 10:51 UTC, niladic commented on app/controllers/ApplicationController.scala
> +              Some(Map()),
👍

2020-11-16 10:52 UTC, niladic commented on typescript/src/application.ts
> +  if (select.value === "Autre") {
ça demande pas mal de refacto, et pour l'instant ça marchait sans. De toutes façons ça ne passera plus quand on ajoutera des contraintes sur le typechecker TS, on fera la refactor à ce moment

2020-11-16 10:53 UTC, niladic commented on typescript/src/application.ts
> +function addInvitedGroupInfos(groupName: string) {
là je garde les blocs du fichier précédent pour la migration, c'est plus facile à lire, ça peut être changé plus tard

2020-11-16 10:53 UTC, niladic commented on conf/evolutions/default/43.sql
> +ALTER TABLE application ADD invited_group_ids varchar[] DEFAULT ARRAY[]::varchar[] NOT NULL;
oups, bien vu

2020-11-16 15:14 UTC, mdulac approved these changes

2020-11-16 15:16 UTC, merged