Utilise les groupes invités pour les stats
betagouv/aplus pull request #825
Opened 2020-11-03 17:26 UTC by niladic

Basé sur https://github.com/betagouv/aplus/pull/820

2020-11-20 16:15 UTC, mdulac requested changes

2020-11-20 16:15 UTC, mdulac commented on app/controllers/ApplicationController.scala
> +          userGroupService
J'ai l'impression qu'on a pas besoin de savoir qu'un group a été rajouté au niveau d'une réponse (ex : `application.answers.exists(_.invitedGroupIds.isEmpty)`. Ce ne serait pas plus simple de tout ramener au niveau de la demande ?
Au pire, on peut toujours faire un champs `allInvitedGroups` (nom non contractuel) dans la demande ayant pour valeur `(invitedGroupIds :: application.answers.flatMap(_.invitedGroupIds)).toSet` ?

2020-11-23 14:27 UTC, niladic commented on app/controllers/ApplicationController.scala
> +          userGroupService
Oui le cas `answers.exists` est problématique maintenant car j'ai fait une refacto sur le `Option[List[UUID]]`. Et j'ai bougé le calcul des groupes invités dans `Application`.

2020-11-23 14:37 UTC, jdauphant commented
ça marche avec les anciennes demandes ?

2020-11-23 14:43 UTC, niladic commented
ça marche "aussi bien qu'avant" avec les anciennes demandes

2020-11-23 15:35 UTC, mdulac approved these changes

2020-11-23 16:16 UTC, merged