Corrige les emails de groupe
betagouv/aplus pull request #826
Opened 2020-11-03 17:27 UTC by niladic

Basé sur https://github.com/betagouv/aplus/pull/820

2020-11-09 18:23 UTC, jdauphant commented on app/services/NotificationService.scala
> +      if (legacyCase) {
on peut avoir des commentaires ici ?
LegacyCase c'est quoi ? c'est des anciennes demandes sans groupe ?

2020-11-09 18:27 UTC, jdauphant reviewed
Je ne vois pas de soucis. 
C'est bien une première étape, il y aura plus de chose de faite ensuite, je suppose (stats par exemple).
J'afficherais les groupes dans la vue d'une application, au moins pour les admins pour débugger.

2020-11-18 13:53 UTC, niladic commented on app/services/NotificationService.scala
> +  // Note: application does not contains answer at this point
```suggestion
  // Note: application does not contain answer at this point
```

2020-11-20 15:58 UTC, mdulac requested changes

2020-11-20 15:58 UTC, mdulac commented on app/services/NotificationService.scala
> +    val (groups, oldGroupIds): (List[UserGroup], Set[UUID]) =
Je ne comprends pas trop le groups et oldGroupIds (je sais que c'était déjà présent avant ce refacto).
`.map(generateNotificationBALEmail(application, answer.some, users))` Cette ligne a l'air d'utiliser oldGroupIds, mais je ne trouve pas ça très clair.
S'il n'y a pas de `answer` passé en paramètre, ça envoie un mail avec `nouvelle demande en sujet, mais c'est appelé dans la méthode `newAnswer`... ça me perds un peu

2020-11-20 15:58 UTC, mdulac commented on app/services/NotificationService.scala
>        .map(generateNotificationBALEmail(application, Some(answer), users))
Je remplacerai bien les deux blocs d'envoi aux groupes par ce bloc :
```
groups.collect {
      case group if oldGroupIds.contains(group.id) =>
        generateNotificationBALEmail(application, answer.some, users)(group)
      case group if !oldGroupIds.contains(group.id) =>
        generateNotificationBALEmail(application, Option.empty[Answer], users)(group)
    }.foreach(sendMail)
```

(et plus globalement tous les `filter` / `map`)

2020-11-20 15:58 UTC, mdulac commented on app/services/NotificationService.scala
> +          users.filter(user => application.invitedUsers.contains(user.id)).flatMap(_.groupIds).toSet
Ici on vérifie que les `users` appartiennent aux `invitedUsers`, mais les `users` ont été récupérés via `userService.byIds((application.invitedUsers ++ answer.invitedUsers).keys)`

Donc d'après ma compréhension de la chose, c'est censé être toujours le cas ?

2020-11-23 04:51 UTC, mdulac commented on app/services/NotificationService.scala
> +          users.filter(user => application.invitedUsers.contains(user.id)).flatMap(_.groupIds).toSet
À moins qu'on veuille séparer les users provenant de `invitedUsers` et ceux de `answer.invitedUsers`. Dans ce cas-là, l'intention serait plus claire en faisant 2 requêtes puis zip, IMO.

2020-11-23 16:35 UTC, niladic commented on app/services/NotificationService.scala
>        .map(generateNotificationBALEmail(application, Some(answer), users))
Oui ici c'est plus simple. Par contre je suis pas convaincu que `collect` soit toujours plus facile à lire que `filter+map`

2020-11-23 16:41 UTC, niladic commented on app/services/NotificationService.scala
> +          users.filter(user => application.invitedUsers.contains(user.id)).flatMap(_.groupIds).toSet
Là c'est "la" méthode pour récup les groupes d'une demande. L'idée c'est de la supprimer, j'ai pas trop envie de la changer pour quelques semaines.

2020-11-23 16:43 UTC, niladic commented on app/services/NotificationService.scala
> +    val legacyCase = application.answers.exists(_.invitedGroupIds.isEmpty) ||
Du coup je me rebase sur l'autre PR où je l'ai renommée `application.isWithoutInvitedGroupIdsLegacyCase`

2020-11-23 16:46 UTC, niladic commented on app/services/NotificationService.scala
> +    val (groups, oldGroupIds): (List[UserGroup], Set[UUID]) =
Oui pour ta première remarque, je renomme en `alreadyPresentGroupIds` et `allGroups`. Pour ta 2ème remarque, comme les groupes sont nouvellement ajoutés, ça fait sens que ce soit une nouvelle demande pour eux.

2020-11-23 18:03 UTC, mdulac approved these changes

2020-11-23 19:13 UTC, merged