Update welcome.scala.html
betagouv/aplus pull request #842
Opened 2020-11-13 17:15 UTC by DanielBMY

ajout de l'accès à  : 
- la documentation d'A+,
- la vidéo de démarrage rapide (focus dessus),
- la page d'inscription aux prochaines formations

2020-11-13 18:02 UTC, mdulac requested changes

2020-11-13 18:08 UTC, mdulac commented on app/views/emails/welcome.scala.html
> +        Lancez-vous sans attendre grâce à la vidéo "<a href="https://docs.aplus.beta.gouv.fr/videos#administration-demarrage-rapide">Administration+ : Démarrage rapide</a>" !<br />
Ok je viens de comprendre, je pensais que c'était une erreur, mais c'est pour encadrer _Administration+ : Démarrage rapide_

2020-11-13 18:09 UTC, mdulac approved these changes

2020-11-13 18:09 UTC, DanielBMY commented on app/views/emails/welcome.scala.html
> +        Lancez-vous sans attendre grâce à la vidéo "<a href="https://docs.aplus.beta.gouv.fr/videos#administration-demarrage-rapide">Administration+ : Démarrage rapide</a>" !<br />
ah mais en fait tt ça n'apporte rien ! (héritage d'une version antérieure où je faisais apparaître l'URL) > on peut tout faire sauter en vrai

2020-11-13 18:12 UTC, mdulac commented on app/views/emails/welcome.scala.html
> +        Lancez-vous sans attendre grâce à la vidéo "<a href="https://docs.aplus.beta.gouv.fr/videos#administration-demarrage-rapide">Administration+ : Démarrage rapide</a>" !<br />
Je te laisse faire les changements ?

2020-11-16 10:20 UTC, niladic commented on app/views/emails/welcome.scala.html
> +        Pour vous familiariser en toute autonomie avec l’outil, des vidéos (webinaires) sont à votre disposition dans le menu de gauche de la <a href="https://docs.aplus.beta.gouv.fr">documentation d
```suggestion
        Pour vous familiariser en toute autonomie avec l’outil, des vidéos (webinaires) sont à votre disposition dans le menu de gauche de la <a href="https://docs.aplus.beta.gouv.fr">documentation d’Administration+</a><br />
```
apostrophe courbe

2020-11-16 10:27 UTC, mdulac commented on app/views/emails/welcome.scala.html
> +        Pour vous familiariser en toute autonomie avec l’outil, des vidéos (webinaires) sont à votre disposition dans le menu de gauche de la <a href="https://docs.aplus.beta.gouv.fr">documentation d
:D

2020-11-16 11:28 UTC, merged