Edition du profil utilisateur
betagouv/aplus pull request #858
Opened 2020-11-19 11:29 UTC by mdulac

2020-11-20 08:06 UTC, DanielBMY commented
on met un champ répétable pour le téléphone ou un champ plus explicite ? 
ex : certains utilisateurs nous communiquent aussi leur portable pro _(typiquement ceux qui alternent entre site principal et bus itinérant)_

2020-11-20 10:20 UTC, mdulac commented
> on met un champ répétable pour le téléphone ou un champ plus explicite ?
> ex : certains utilisateurs nous communiquent aussi leur portable pro _(typiquement ceux qui alternent entre site principal et bus itinérant)_

Ok, en effet il faut qu'on gère ça, tu en avais déjà parlé d'ailleurs? Mais ça nécessite de reprendre tous les champs de saisie des numéros (sauf si on accepte la saisie libre)

2020-11-23 13:09 UTC, Aurelie-J approved these changes

2020-11-23 15:37 UTC, mdulac commented
> on met un champ répétable pour le téléphone ou un champ plus explicite ?
> ex : certains utilisateurs nous communiquent aussi leur portable pro _(typiquement ceux qui alternent entre site principal et bus itinérant)_

On en a discuté avec Alex ce matin : ça rentrerai dans le cadre de l'ajout du champs "admin" en saisie libre qu'Alex avait proposé. ça irait ?

2020-11-24 14:23 UTC, niladic requested changes

2020-11-24 14:23 UTC, niladic commented on app/views/editProfile.scala.html
> +                    font-weight: bold;">@form.globalErrors.mkString(", ")</div>
tu peux créer une classe CSS plutôt ?

2020-11-24 14:23 UTC, niladic commented on app/services/UserService.scala
> +      val normalizedQualite = qualite.normalized
`StringHelper.commonStringInputNormalization` a été créée pour ça

2020-11-24 14:23 UTC, niladic commented on app/models/formModels.scala
> +          )
Je pense qu'il vaut mieux d'abord supprimer les espaces et ensuite vérifier les 10 chiffres (quitte à refaire la suppression + re-split avant d'enregistrer en BDD).

2020-11-24 14:23 UTC, niladic commented on app/models/formModels.scala
> +          "email" -> email.verifying(emailAddress, maxLength(200), nonEmpty),
Les regex qui valident des emails j'y crois pas, un email marche ou marche pas, mais c'est impossible à valider. Je pense que tu devrais juste utiliser `ignore`

2020-11-24 14:56 UTC, mdulac commented on app/models/formModels.scala
> +          "email" -> email.verifying(emailAddress, maxLength(200), nonEmpty),
Oui en effet, c'est une erreur de ma part. De toute manière on ne doit surtout pas lire l'email du form, puisqu'il ne doit pas être édité.

2020-11-24 14:56 UTC, mdulac commented on app/controllers/UserController.scala
> +              import userService.{editProfile => edit}
Toujours pour les mêmes raisons :)

2020-11-24 14:56 UTC, mdulac commented on app/controllers/UserController.scala
> +      import eventService._
Toujours pour les mêmes raisons :)

2020-11-24 15:05 UTC, mdulac commented on app/views/editProfile.scala.html
> +                    font-weight: bold;">@form.globalErrors.mkString(", ")</div>
Yes, et il faudra changer toutes les vues avec cette classe, à terme

2020-11-24 15:27 UTC, mdulac commented on app/models/formModels.scala
> +          )
En fait j'avais pas fait gaffe, mais ne vaut-il mieux pas enregistrer le numéro dans espace en BDD ?

2020-11-24 16:07 UTC, niladic commented on app/models/formModels.scala
> +          )
ça a ses avantages et inconvénients :D , 4 caractères de plus (inconvénient), plus facile à lire sur d'éventuels exports/metabase (avantage)

2020-11-24 16:46 UTC, jdauphant commented
Vous pouvez ajouter des infos pratiques non éditable comme les groupes ? (ça permet à la personnes de le savoir)

2020-11-24 18:23 UTC, niladic approved these changes

2020-11-25 17:09 UTC, merged

2020-11-25 17:10 UTC, jdauphant commented
Les numéros en Martinique et co, sont aussi en XX XX XX XX XX ? cc @DanielBMY

2020-11-25 17:11 UTC, jdauphant commented
vous savez chaque contrainte peut être une peine pour certains utilisateurs en prod.
Il y a des personnes avec des noms avec une seule lettre, des personnes sans nom, des personnes avec plusieurs prénoms. Des numéros de téléphone des DOM/TOM.
Il ne faut pas chercher à normaliser pour normaliser.