Optimise 2 méthodes lentes dans le rendu des stats
betagouv/aplus pull request #864
Opened 2020-11-23 18:49 UTC by niladic

Optimisation de `applicationsGroupedByMonth` et `closedApplicationsGroupedByMonth`

2020-11-23 19:13 UTC, jdauphant reviewed
Ah, c'est limité par les calculs ? pas la DB ou la taille des données ?
On pourra voir en prod

2020-11-23 19:17 UTC, niladic commented
J'ai juste testé en local. Les méthodes que j'ai corrigé sont quadratiques dans le nombre de demandes avec un calcul non trivial de date. Mais elles restent 5x plus rapides que https://github.com/betagouv/aplus/pull/865

2020-11-23 19:23 UTC, jdauphant commented
c'est le pie chart qui bouffer tout le temps ?

2020-11-23 19:24 UTC, jdauphant commented
on va voir en prod ce que ça donne, on peut les passer en séparer pour comparer ? (le pie chart en premier)

2020-11-23 19:24 UTC, jdauphant commented
(ou osef)

2020-11-23 19:26 UTC, niladic commented
plus simple : on passe en preprod master sans le pie chart, on essaye puis on passe master avec cette PR en preprod

2020-11-24 13:56 UTC, mdulac requested changes

2020-11-24 13:56 UTC, mdulac commented on app/helper/Time.scala
> +  def monthsBetween(fromDate: ZonedDateTime, toDate: ZonedDateTime): List[YearMonth] = {
Je ne pense pas que `ZonedDateTime` soit le type le plus approprié pour calculer le diff entre 2 dates tronquées au jour. `LocalDate` ferait l'affaire, et l'avantage c'est qu'on peut faire un truc du style :

```
def monthsBetween(fromDate: LocalDate, toDate: LocalDate): List[YearMonth] = {
    val start = fromDate.withDayOfMonth(1)
    start
      .datesUntil(toDate, Period.ofMonths(1))
      .map(date => YearMonth.from(date))
      .collect(Collectors.toList())
      .asScala
      .toList
  }
```

On peut peut-être même retourner des `LocalDate` plutôt que des `YearMonth`, et le `DateTimeFormatter` fonctionnera tout aussi bien.

```
def monthsBetween(fromDate: LocalDate, toDate: LocalDate): List[LocalDate] = {
    val start = fromDate.withDayOfMonth(1)
    start
      .datesUntil(toDate, Period.ofMonths(1))
      .collect(Collectors.toList())
      .asScala
      .toList
  }
```

L'avantage de ça, c'est qu'on peut utiliser la même méthode (en changeant `Period.ofMonths(1)` par `Period.ofWeeks(1)`) pour refactoriser la méthode concernant les semaines.

```
def weeksBetween(fromDate: LocalDate, toDate: LocalDate): List[LocalDate] = {
    val start = fromDate.withDayOfMonth(1)
    start
      .datesUntil(toDate, Period.ofWeeks(1))
      .collect(Collectors.toList())
      .asScala
      .toList
  }
```

WDYT ?

2020-11-24 14:57 UTC, niladic commented on app/helper/Time.scala
> +  def monthsBetween(fromDate: ZonedDateTime, toDate: ZonedDateTime): List[YearMonth] = {
Je connaissais pas `datesUntil` c'est java 9 ? N'oublie pas qu'on est sur la v8. Par contre sur cette méthode je préfère retourner des `YearMonth` car c'est une optimisation. Mais je ne sais pas à quel point cette PR va impacter la prod.

2020-11-30 14:55 UTC, merged