Group management (WIP)
betagouv/aplus pull request #876
Opened 2020-11-27 16:28 UTC by mdulac

2020-12-02 18:56 UTC, niladic requested changes

2020-12-02 18:56 UTC, niladic commented on app/models/EventType.scala
> +  object EditMyGroupUpdatedWarn extends Warn
que penses-tu de 
```suggestion
  object EditMyGroupBadUserInput extends Warn
```

2020-12-02 18:56 UTC, niladic commented on app/controllers/UserController.scala
> +            Redirect(routes.UserController.showEditMyGroups()).flashing("error" -> message)
tu devrais plutôt mettre un message plus compréhensible pour les utilisateurs, plutôt que le `getMessage` d'une exception

2020-12-02 18:56 UTC, niladic commented on app/views/editMyGroups.scala.html
> +                @if(user.id != currentUser.id) {
ah mince cats n'est pas importé ?
```suggestion
                @if(user.id =!= currentUser.id) {
```

2020-12-02 18:56 UTC, niladic commented on app/views/editMyGroups.scala.html
> +                        <span class="application__anwsers">@applications.count(_.creatorUserId == user.id) demandes</span>
```suggestion
                        <span class="application__anwsers">@applications.count(_.creatorUserId === user.id) demandes</span>
```

2020-12-02 18:56 UTC, niladic commented on app/views/editMyGroups.scala.html
> +                    <div id="answers-90500d58-4345-4538-a1d7-ff80e87b5398" class="vertical-align--middle">
ahahah tu es tellement grillé !

2020-12-02 18:56 UTC, niladic commented on app/views/editMyGroups.scala.html
> +        <div style="margin-top: 24px;
évite la property `style` c'est un truc qu'on veut interdire à terme

2020-12-02 18:56 UTC, niladic commented on app/controllers/UserController.scala
> +                    val message = "L’utilisateur n'existe pas dans Administration+"
```suggestion
                    val message = "L’utilisateur n’existe pas dans Administration+"
```

2020-12-02 18:56 UTC, niladic commented on app/views/editMyGroups.scala.html
> +                        @helper.input(form("email"), "label" -> "Adresse email de l'utilisateur") { (id, name, value, args) =>
```suggestion
                        @helper.input(form("email"), "label" -> "Adresse email de l’utilisateur") { (id, name, value, args) =>
```

2020-12-02 18:56 UTC, niladic commented on app/views/editMyGroups.scala.html
> +                            Ajouter l'utilisateur</button>
```suggestion
                            Ajouter l’utilisateur</button>
```

2020-12-03 00:17 UTC, mdulac commented on app/views/editMyGroups.scala.html
> +                    <div id="answers-90500d58-4345-4538-a1d7-ff80e87b5398" class="vertical-align--middle">
Qu'est-ce que ça fout là ?! 😅
Copier-coller inattendu

2020-12-03 00:18 UTC, mdulac commented on app/views/editMyGroups.scala.html
> +        <div style="margin-top: 24px;
J'ai oublié de le retirer, ça vient de la vue dont je me suis inspiré. Je ferai une classe.

2020-12-03 00:18 UTC, mdulac commented on app/controllers/UserController.scala
> +                    val message = "L’utilisateur n'existe pas dans Administration+"
Un oubli. Mais il y a du mieux, j'en ai mis plein d'autres 😄

2020-12-03 00:20 UTC, mdulac commented on app/models/EventType.scala
> +  object EditMyGroupUpdatedWarn extends Warn
Ça me va, mais je pensais qu'il existait une convention pour les noms d'événements, d'où ce choix de nom

2020-12-03 00:23 UTC, mdulac commented on conf/routes
> +GET         /groups/:groupId/remove/:userId                                                  controllers.UserController.removeFromGroup(userId: java.util.UUID, groupId: java.util.UUID)
Je sais que c'est pas fou, mais j'ai vu qu'il existait déjà des routes d'écriture en GET. Donc j'y suis allé tu schuss, sans les mains 😄

2020-12-03 00:24 UTC, mdulac commented on app/models/User.scala
> +  def belongsTo(groupId: UUID) = this.groupIds.contains[UUID](groupId)
Pas particulièrement, c'était instinctif 😄

2020-12-03 00:27 UTC, mdulac commented on app/controllers/UserController.scala
> +            Redirect(routes.UserController.showEditMyGroups()).flashing("error" -> message)
Ça me va aussi. Comme sur le message d'erreur il est écrit "contactez le support", je trouvais que c'était judicieux de mettre l'erreur technique pour avoir du détail par l'utilisateur. Après c'est vrai qu'on peut le retrouver dans les évènements..

2020-12-03 00:27 UTC, mdulac commented on app/views/editMyGroups.scala.html
> +                        <span class="application__anwsers">@applications.count(_.creatorUserId == user.id) demandes</span>
Je n'avais pas percuté qu'on pouvait utiliser Cats dans Twirl

2020-12-03 00:30 UTC, mdulac commented on conf/routes
> +GET         /groups/:groupId/remove/:userId                                                  controllers.UserController.removeFromGroup(userId: java.util.UUID, groupId: java.util.UUID)
Mais je suis chaud pour migrer les routes d'écriture en POST pour les autres occurences

2020-12-07 13:46 UTC, niladic commented on conf/routes
> +GET         /groups/:groupId/remove/:userId                                                  controllers.UserController.removeFromGroup(userId: java.util.UUID, groupId: java.util.UUID)
Je n'avais jamais remarqué les `GET` non nilpotents, mais ouais il y en a au moins 3... Il vaut mieux pas perpétuer une mauvaise pratique.

2020-12-07 13:48 UTC, niladic commented on app/models/EventType.scala
> +  object EditMyGroupUpdatedWarn extends Warn
ah non il n'y a pas de convention, tu es libre de choisir les noms que tu penses être les plus compréhensibles

2020-12-07 16:54 UTC, niladic commented on app/models/formModels.scala
> +        mapping("email" -> nonEmptyText)(AddUserToGroupFormData.apply)(
après test, c'est pas super d'avoir une erreur si on a mis une espace
```suggestion
        mapping("email" -> nonEmptyText)(email => AddUserToGroupFormData(email.trim))(
```

2020-12-07 16:54 UTC, niladic commented on app/controllers/UserController.scala
> +            val message = "Le groupe a été modifié"
```suggestion
            val message = "L’utilisateur a bien été retiré du groupe."
```

2020-12-14 23:21 UTC, jdauphant commented
"On ne peut pas ajouter un utilisateur qui n'est pas déjà utilisateur d'Administration+" -> ça ne pose pas soucis de le faire, c'est même pratique de le permettre

2020-12-15 09:38 UTC, mdulac commented
> "On ne peut pas ajouter un utilisateur qui n'est pas déjà utilisateur d'Administration+" -> ça ne pose pas soucis de le faire, c'est même pratique de le permettre

Pour moi, c'était un step 2, dans une prochaine PR.
ça nécessite de gérer les notifications par mail, et créer les token, ...

2020-12-15 14:04 UTC, jdauphant commented
> > "On ne peut pas ajouter un utilisateur qui n'est pas déjà utilisateur d'Administration+" -> ça ne pose pas soucis de le faire, c'est même pratique de le permettre
> 
> Pour moi, c'était un step 2, dans une prochaine PR.
> ça nécessite de gérer les notifications par mail, et créer les token, ...

Ok, c'est noté, peut être en glisser un mot à l'utilisateur (avec une petite phrase, c'est peut être déjà fait)

2020-12-21 10:44 UTC, niladic approved these changes

2020-12-21 10:48 UTC, merged