No jackson-databind upgrade
betagouv/aplus pull request #883
Opened 2020-12-02 15:49 UTC by mdulac

2020-12-03 00:40 UTC, mdulac commented
Pour "x.y.z", faire une règle pour update seulement "z" avec https://github.com/scala-steward-org/scala-steward/blob/master/docs/faq.md#how-can-version-updates-be-controlled

2020-12-07 10:26 UTC, niladic requested changes

2020-12-07 10:26 UTC, niladic commented on .scala-steward.conf
> +updates.ignore = [ { groupId = "com.fasterxml.jackson.core", artifactId = "jackson-databind", version="x.y." } ]
d'après la doc c'est `updates.pin` https://github.com/scala-steward-org/scala-steward/blob/master/docs/faq.md#how-can-version-updates-be-controlled
```suggestion
updates.pin = [ { groupId = "com.fasterxml.jackson.core", artifactId = "jackson-databind", version="x.y." } ]
```

2020-12-07 10:38 UTC, mdulac commented on .scala-steward.conf
> +updates.ignore = [ { groupId = "com.fasterxml.jackson.core", artifactId = "jackson-databind", version="x.y." } ]
Bien vu 👍

2020-12-07 11:03 UTC, niladic approved these changes

2020-12-07 16:13 UTC, merged